day_products = [
    'airmass',
    'ash',
    'cloud_phase_distinction',
    'cloud_phase_distinction_raw',
    'cloudtop',
    'cloudtop_daytime',
    'colorized_ir_clouds',
    'convection',
    'day_microphysics',
    'day_microphysics_winter',
    'dust',
    'fog',
    'green_snow',
    'hrv_clouds',
    'hrv_fog',
    'hrv_severe_storms',
    'hrv_severe_storms_masked',
    'ir108_3d',
    'ir_cloud_day',
    'ir_overview',
    'ir_sandwich',
    'natural_color',
    'natural_color_nocorr',
    'natural_color_raw',
    'natural_color_raw_with_night_ir',
    'natural_color_with_night_ir',
    'natural_color_with_night_ir_hires',
    'natural_enh',
    'natural_enh_with_night_ir',
    'natural_enh_with_night_ir_hires',
    'natural_with_night_fog',
    # 'night_fog',
    # 'night_ir_alpha',
    # 'night_ir_with_background',
    # 'night_ir_with_background_hires',
    # 'night_microphysics',
    'overview',
    'overview_raw',
    'realistic_colors',
    'rocket_plume_day',
    'rocket_plume_night',
    'snow',
    'vis_sharpened_ir'
]

night_products = [
    'night_fog',
    'night_ir_alpha',
    'night_ir_with_background',
    'night_ir_with_background_hires',
    'night_microphysics',
]

all_bands=[
    'HRV',
    'IR_016',
    'IR_039',
    'IR_087',
    'IR_097',
    'IR_108',
    'IR_120',
    'IR_134',
    'VIS006',
    'VIS008',
    'WV_062',
    'WV_073',
]
    
export = day_products, night_products, all_bands